### ISSUE TITLE
The missing visualization tool mentioned by documentation

### ISSUE THREAD

**Issue by buxiangqimingle233** [tenstorrent/tt-buda#59]
The tt-buda [doc](https://docs.tenstorrent.com/pybuda/latest/advanced_user_guide.html) mentioned a great tool named reportify to visualize the computation graph and task mapping result, but this tool seems to be inaccessible now. Is there any approach to get it?

**Comment by Kami-prog** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by jhlee508** [comment]
As an alternative, using [route-ui](https://github.com/tenstorrent/route-ui) seems like a good option for now.

**Comment by milank94** [comment]
@buxiangqimingle233 Reportify was not released publicly due to the priority shift to focus on TT-Forge/TT-MLIR and TT-Metalium development. It's a tool that wont be actively managed. 

If you do want to get access to it, I can give you an offline drop. Please reach out to me if interested mkordic@tenstorrent.com
